# -*- coding: utf-8 -*-
"""MachineLearning_With_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYKvzxgZjZ42Hso3KIy209KogNtx4wi9
"""

# Import Data Manipulation Libraries
import numpy as np
import pandas as pd
# Import Filter Warning Libraries
import warnings
warnings.filterwarnings(action = 'ignore')
# Import scikit-learn Libraries
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn import set_config
set_config(display='diagram')

# Define Configuration
filepath = r'C:\cement_MLModel_deployment\Concrete_Data.csv'
target_col = 'Concrete compressive strength(MPa, megapascals) '
drop_col = []

# Step1: Data Ingestion

df = pd.read_csv(filepath)
df.columns

# Remove duplicates
df = df.drop_duplicates()

# Separate X and y FIRST
X = df.drop(columns=[target_col])
y = df[target_col]

# Identify columns from X, NOT df
numerical_data = X.select_dtypes(exclude='object').columns.tolist()
categorical_data = X.select_dtypes(include='object').columns.tolist()

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)

# Numerical Pipeline
numerical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

# Categorical Pipeline
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(
        drop='first',
        handle_unknown='ignore',
        sparse_output=True
    ))
])

# Column Transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('numerical', numerical_pipeline, numerical_data),
        ('categorical', categorical_pipeline, categorical_data)
    ]
)

# Model Pipeline
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=50,
        random_state=1,
        n_jobs=-1
    ))
])

# Fit
model_pipeline.fit(X_train, y_train)

# Prediction
y_pred = model_pipeline.predict(X_test)

score = r2_score(y_test,y_pred)
print(f'The Model Score is {score}')

model_pipeline

import pickle
pickle.dump(model_pipeline, open('model.pkl', 'wb'))